// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:vistacortex_new_features/features/reminders/models/reminder.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ReminderAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ReminderAdapter());
  }
}
